/**
 * 공통 에러 코드 정의
 */
export const ErrorCode = {
  // Store
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  INVALID_STORE_CODE: 'INVALID_STORE_CODE',
  INVALID_STORE_NAME: 'INVALID_STORE_NAME',

  // Table
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  INVALID_TABLE_NUMBER: 'INVALID_TABLE_NUMBER',
  DUPLICATE_TABLE_NUMBER: 'DUPLICATE_TABLE_NUMBER',

  // Session
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_NOT_ACTIVE: 'SESSION_NOT_ACTIVE',
  SESSION_ALREADY_COMPLETED: 'SESSION_ALREADY_COMPLETED',
  ACTIVE_SESSION_EXISTS: 'ACTIVE_SESSION_EXISTS',
  INVALID_SESSION_TOKEN: 'INVALID_SESSION_TOKEN',

  // Category
  INVALID_CATEGORY_NAME: 'INVALID_CATEGORY_NAME',
  DUPLICATE_CATEGORY_NAME: 'DUPLICATE_CATEGORY_NAME',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_ORDERS: 'CATEGORY_HAS_ORDERS',
  INVALID_SORT_ORDER: 'INVALID_SORT_ORDER',

  // Menu
  INVALID_MENU_NAME: 'INVALID_MENU_NAME',
  INVALID_PRICE: 'INVALID_PRICE',
  INVALID_DESCRIPTION: 'INVALID_DESCRIPTION',
  MENU_NOT_FOUND: 'MENU_NOT_FOUND',
  MENU_NOT_AVAILABLE: 'MENU_NOT_AVAILABLE',

  // Image
  INVALID_IMAGE_FORMAT: 'INVALID_IMAGE_FORMAT',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  IMAGE_UPLOAD_FAILED: 'IMAGE_UPLOAD_FAILED',

  // Order
  EMPTY_ORDER: 'EMPTY_ORDER',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  AMOUNT_MISMATCH: 'AMOUNT_MISMATCH',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  UNAUTHORIZED_STATUS_CHANGE: 'UNAUTHORIZED_STATUS_CHANGE',
  ORDER_ALREADY_COMPLETED: 'ORDER_ALREADY_COMPLETED',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

const ERROR_STATUS_MAP: Record<string, number> = {
  [ErrorCode.STORE_NOT_FOUND]: 404,
  [ErrorCode.TABLE_NOT_FOUND]: 404,
  [ErrorCode.SESSION_NOT_FOUND]: 401,
  [ErrorCode.SESSION_EXPIRED]: 401,
  [ErrorCode.CATEGORY_NOT_FOUND]: 404,
  [ErrorCode.MENU_NOT_FOUND]: 404,
  [ErrorCode.ORDER_NOT_FOUND]: 404,
  [ErrorCode.DUPLICATE_TABLE_NUMBER]: 409,
  [ErrorCode.DUPLICATE_CATEGORY_NAME]: 409,
  [ErrorCode.ACTIVE_SESSION_EXISTS]: 409,
  [ErrorCode.CATEGORY_HAS_ORDERS]: 409,
  [ErrorCode.IMAGE_UPLOAD_FAILED]: 500,
};

/**
 * 애플리케이션 에러 클래스
 */
export class AppError extends Error {
  public readonly code: ErrorCodeType;
  public readonly statusCode: number;

  constructor(code: ErrorCodeType, message: string, statusCode?: number) {
    super(message);
    this.name = 'AppError';
    this.code = code;
    this.statusCode = statusCode ?? ERROR_STATUS_MAP[code] ?? 400;
  }

  toJSON() {
    return {
      error: {
        code: this.code,
        message: this.message,
      },
    };
  }
}
